name: EkaMurder
main: fr.ekazuki.ekamurder.EkaMurder
version: 0.1
author: ekazuki
website: https://ekazuki.fr
api-version: 1.15
commands:
   murder:
      description: Murder command
      usage: /murder <arg>